### ISSUE TITLE
test環境が構築できない

### ISSUE THREAD

**Issue by hiyoko3** [naruhiyo/naruhiyo.github.io#2]
- jest
- storybook

が動かない。
`jest` に関しては動く人もいるかも。。

`storybook`のエラーは下記の通り

```
ERROR in ./.storybook/config.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/tatsuya/virtualOS/code/front/naruhiyo.github.io/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/Users/tatsuya/virtualOS/code/front/naruhiyo.github.io/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/tatsuya/virtualOS/code/front/naruhiyo.github.io/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/tatsuya/virtualOS/code/front/naruhiyo.github.io/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/tatsuya/virtualOS/code/front/naruhiyo.github.io/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/tatsuya/virtualOS/code/front/naruhiyo.github.io/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/tatsuya/virtualOS/code/front/naruhiyo.github.io/node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at /Users/tatsuya/virtualOS/code/front/naruhiyo.github.io/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Users/tatsuya/virtualOS/code/front/naruhiyo.github.io/node_modules/@babel/core/lib/config/config-chain.js:120:22)
    at loadPrivatePartialConfig (/Users/tatsuya/virtualOS/code/front/naruhiyo.github.io/node_modules/@babel/core/lib/config/partial.js:85:55)
    at Object.loadPartialConfig (/Users/tatsuya/virtualOS/code/front/naruhiyo.github.io/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/Users/tatsuya/virtualOS/code/front/naruhiyo.github.io/node_modules/babel-loader/lib/index.js:144:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/tatsuya/virtualOS/code/front/naruhiyo.github.io/node_modules/babel-loader/lib/index.js:3:103)
    at _next (/Users/tatsuya/virtualOS/code/front/naruhiyo.github.io/node_modules/babel-loader/lib/index.js:5:194)
    at /Users/tatsuya/virtualOS/code/front/naruhiyo.github.io/node_modules/babel-loader/lib/index.js:5:364
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true main[2]

```

**Comment by hiyoko3** [comment]
- storybook は`feature/create-test-env`にて動作を確認

**Comment by hiyoko3** [comment]
- 今回はWebページのみでモジュールを開発していないため、ユニットテストとE2Eテストは必要ないと判断しました。

以上から、このチケットはクローズします。
